name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-version: 'latest'

      - name: Authenticate to Salesforce
        run: |
          echo $SF_USERNAME | sfdx org:login:web --username $SF_USERNAME --password $SF_PASSWORD --securitytoken $SF_SECURITY_TOKEN --setdefaultusername --instanceurl $SFDC_AUTH_URL

      - name: Run Linting (LWC and Apex)
        run: |
          # You can add linting commands here if needed, for example:
          # npm run lint for LWC or sfdx force:apex:test:run for Apex tests
          sfdx force:apex:test:run --resultformat human --wait 10

      - name: Run Unit Tests
        run: |
          sfdx force:apex:test:run --resultformat human --wait 10

      - name: Deploy to Salesforce Sandbox
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --testlevel RunLocalTests

      - name: Send Notification on Success
        uses: slackapi/slack-github-action@v1
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          channel-id: 'your-slack-channel-id'
          text: 'Deployment was successful!'

      - name: Send Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          channel-id: 'your-slack-channel-id'
          text: 'Deployment failed!'
