name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-version: 'latest'

      - name: Authenticate to Salesforce
<<<<<<< HEAD
        uses: jawills/sf-deploy@v1.0
        with: 
          SFDC_AUTH_URL: ${{secrets.SFDC_AUTH_URL}}
=======
        run: |
          echo $SF_USERNAME | sfdx org:login:web --username $SF_USERNAME --password $SF_PASSWORD --securitytoken $SF_SECURITY_TOKEN --setdefaultusername --instanceurl $SFDC_AUTH_URL
>>>>>>> 8062ff3095dba34f7b6eb2b13188da60a5e248aa

      - name: Run Linting (LWC and Apex)
        run: |
<<<<<<< HEAD
          sfdx force:apex:test:run --resultformat human --tests "TestDealTrigger"
=======
          # You can add linting commands here if needed, for example:
          # npm run lint for LWC or sfdx force:apex:test:run for Apex tests
          sfdx force:apex:test:run --resultformat human --wait 10
>>>>>>> 8062ff3095dba34f7b6eb2b13188da60a5e248aa

      - name: Run Unit Tests
        run: |
          sfdx force:apex:test:run --resultformat human --wait 10

      - name: Deploy to Salesforce Sandbox
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --testlevel RunLocalTests
