name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      # Step 3: Authenticate to Salesforce
      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.SFDC_AUTH_URL }}" > sfdc_auth_url.txt
          sfdx force:auth:sfdxurl:store -f sfdc_auth_url.txt -s -a myOrg

      # Step 6: Deploy to Salesforce (if tests pass)
      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u ${{secrets.SF_USERNAME}}
