name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-version: 'latest'

      - name: Authenticate to Salesforce
        uses: jawills/sf-deploy@v1.0
        with: 
          SFDC_AUTH_URL: ${{secrets.SFDC_AUTH_URL}}

      - name: Run Linting
        run: |
          sfdx force:apex:test:run --resultformat human --tests "TestDealTrigger"

      - name: Run Unit Tests
        run: |
          sfdx force:apex:test:run --resultformat human --wait 10

      - name: Deploy to Salesforce Sandbox
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --testlevel RunLocalTests
